// 워들들 단어 목록 — 5글자 영단어
export const ANSWERS: string[] = [
  // A
  'abbey','abbot','abhor','abide','abode','abort','abyss','ached','acorn','acrid',
  'adapt','adept','admit','adobe','adore','adorn','agave','agile','aglow','agony',
  'afoot','aisle','allay','alley','allot','allow','alloy','altar','alter','amaze',
  'amber','amble','amend','ample','amuse','angel','anger','angle','ankle','annex',
  'antic','anvil','aorta','apple','apply','apron','aptly','arbor','ardor','arena',
  'aroma','arose','array','arrow','askew','avoid','awake','aware','awful','azure',
  // B
  'badge','bagel','bayou','beach','beard','beast','began','below','bench','berth',
  'birch','bison','black','blade','blame','bland','blast','blaze','bleak','blend',
  'bless','blind','bliss','blitz','block','blood','bloom','blown','blues','blunt',
  'bloke','board','bonus','boost','booth','bound','boxer','brace','brain','brave',
  'brawl','brawn','breed','brine','brick','brief','bring','broad','brook','brown',
  'broth','brute','brush','buddy','budge','bugle','bulge','build','built','bunch',
  'bumpy','burly','burnt','burst','buyer','bushy','butch','byway',
  // C
  'cabin','cable','canoe','canny','candy','cargo','carol','carry','caste','catch',
  'caulk','cause','cedar','cease','chafe','champ','chair','chalk','chaos','chasm',
  'charm','chart','cheap','check','cheek','cheer','chess','chest','chief','child',
  'china','chive','chimp','churn','cinch','civic','civil','clamp','clank','cleft',
  'clash','class','clean','clear','clerk','click','cliff','climb','cling','clock',
  'clone','close','cloud','clout','cluck','clump','clunk','clung','coast','coach',
  'cocoa','colon','comma','comfy','comet','coral','could','count','court','cover',
  'covet','craft','crane','crank','crash','crawl','crazy','creak','creek','creep',
  'crest','crick','crimp','crisp','croak','crone','croon','cross','crowd','crown',
  'crude','cruel','crush','crust','crypt','cubic','curly','curry','curve','cycle',
  'cutie','cynic',
  // D
  'daily','dance','death','debut','decay','decoy','delay','delta','demon','depot',
  'depth','derby','devil','digit','dirty','disco','dizzy','dodge','doubt','dough',
  'draft','drain','drama','drawn','dream','dress','dried','drink','drive','drone',
  'drove','drown','drugs','drunk','dryer','dusty','dwarf','dwell','dying',
  // E
  'eagle','early','earth','eight','eerie','elbow','elite','ember','empty','enemy',
  'enjoy','enter','entry','equal','error','evade','event','every','exact','exert',
  'exile','extra',
  // F
  'faint','fairy','faith','false','fancy','fatal','feast','fence','fetch','fever',
  'field','fifty','fight','final','first','fixed','flame','flank','flash','fleet',
  'flesh','flock','floor','flour','fluid','flush','focus','force','forge','forth',
  'found','frame','frank','fraud','fresh','front','frost','froze','fruit','fully',
  'funny',
  // G
  'gecko','genre','ghost','giant','given','gland','glass','glaze','gloom','gloss',
  'globe','glove','going','grace','grade','grain','grand','grant','grape','grasp',
  'grass','grave','great','green','greed','greet','grief','grind','groan','groom',
  'group','grove','growl','grown','guard','guide','guild','guilt','guise','gummy',
  'gusto','gypsy',
  // H
  'happy','harsh','haste','hatch','haven','heard','heart','heavy','hedge','herbs',
  'hinge','hoist','honor','horse','hotel','house','human','humor','hurry','husky',
  'hyena',
  // I
  'ideal','image','imply','inane','inbox','index','infer','inner','input','irate',
  'ivory',
  // J
  'jazzy','jewel','joker','judge','juice','juicy','jumbo',
  // K
  'karma','kneel','knife','knock','knoll','known','krill',
  // L
  'label','lance','large','laser','later','layer','lathe','learn','lease','leave',
  'legal','lemon','level','light','lilac','linen','liver','lithe','livid','llama',
  'local','lodge','logic','loose','lover','lower','lucky','lusty','lyric',
  // M
  'magic','major','maker','maple','manor','march','marry','marsh','match','meant',
  'mealy','meaty','medal','merge','merry','metal','might','mince','minor','minus',
  'mirth','miser','mixer','model','money','month','moral','moody','mossy','mourn',
  'motor','motto','mount','mouse','movie','muddy','mummy','murky','music','mushy',
  'musty',
  // N
  'naive','nasal','nasty','natty','naval','nerve','never','niece','nifty','night',
  'ninja','noble','noise','north','noted','novel','nurse','nutty','nymph',
  // O
  'ocean','occur','offer','often','olive','onset','optic','orbit','order','other',
  'otter','ought','outer','outdo','ozone',
  // P
  'paint','panic','paper','party','pasta','patch','patsy','pause','peace','pearl',
  'penny','perch','perky','petty','phase','phone','photo','piano','piece','pilot',
  'pitch','pixel','pizza','place','plaid','plain','plane','plant','plate','plaza',
  'plead','pluck','plume','point','poise','polar','polyp','pouch','power','prank',
  'preen','press','price','prick','pride','prime','print','prior','prism','prize',
  'probe','prose','proud','prove','prowl','prude','psalm','pudgy','pulse','pupil',
  'purse','pygmy',
  // Q
  'queen','query','queue','quick','quiet','quite','quota','quote',
  // R
  'radar','radio','raise','rally','ranch','range','rapid','ratio','reach','ready',
  'rebel','reedy','reign','refer','repay','reset','resin','retro','revel','rider',
  'ridge','rifle','right','risky','river','rival','rivet','roast','robin','rocky',
  'rodeo','rogue','rough','round','route','rowdy','royal','ruddy','ruler','rural',
  'rusty',
  // S
  'saint','sauce','savor','scald','scale','scare','scram','scrap','scrub','scene',
  'scone','scope','score','scout','seedy','seize','sense','serve','serum','seven',
  'shade','shady','shaft','shake','shale','shall','shame','shape','share','shark',
  'sharp','sheer','shelf','shell','shift','shine','shirt','showy','shock','shook',
  'shoot','shore','shown','shrug','siege','since','siren','sixth','sixty','skill',
  'slack','slang','slant','slash','sleep','slice','slide','slime','slink','slope',
  'sloth','slump','small','smart','smile','smoke','snack','snake','snare','sneak',
  'sniff','snore','soggy','solar','solid','solve','sonar','sorry','south','space',
  'spare','spark','spawn','speak','spell','spend','spill','spine','spite','split',
  'spook','spoon','spore','spree','spoke','sport','spray','squat','squid','stack',
  'staff','stage','stain','stale','stall','stamp','stand','stark','start','state',
  'steam','steel','steep','steer','stern','stick','still','stock','stomp','stoop',
  'stone','stood','store','stoke','stole','storm','story','strap','straw','stray',
  'strew','strip','strut','stuck','study','stung','stunk','style','suave','suite',
  'sunny','super','surge','swamp','swear','sweep','sweet','swept','swift','swine',
  'swoop','sword','sworn','syrup',
  // T
  'tabby','taboo','tacky','taffy','taint','taken','talon','tango','tangy','taste',
  'taunt','tawny','teach','tense','tenth','tepid','terse','thane','theta','thick',
  'thigh','thing','think','third','thorn','those','three','threw','throe','throw',
  'thumb','thump','tiara','tidal','tiger','tight','timid','tipsy','tired','title',
  'toast','today','token','tonic','topaz','torch','torso','total','totem','toxic',
  'trace','track','trade','trail','train','trait','trash','treat','trend','trial',
  'tribe','trice','trick','tried','tripe','trite','troll','troop','trout','trove',
  'truck','truce','truly','trunk','truss','truth','tumor','tulip','tunic','tutor',
  'twain','twang','tweed','twerp','twice','twirl','twist','tying',
  // U
  'udder','ultra','uncle','under','unify','union','unite','until','upper','upset',
  'usher','usurp','usual','utter',
  // V
  'valid','valve','value','vapor','vault','vaunt','venom','verge','verse','vibes',
  'vicar','vigil','vigor','villa','vinyl','viper','virus','visit','visor','vista',
  'vital','vivid','vixen','vocal','vodka','voice','vomit','voter','vying',
  // W
  'wacky','wager','waist','waltz','warty','watch','water','weary','wedge','weigh',
  'weird','whale','whack','wheat','wheel','where','whiff','while','whirl','whisk',
  'white','whole','wider','winch','wince','witch','woman','women','woody','world',
  'wordy','worry','worse','worst','worth','would','wrath','wreck','write','wring',
  'wrist','wrong','wrote',
  // X Y Z
  'xenon','yacht','yield','yokel','young','yours','youth','yucca','yummy',
  'zebra','zesty','zippy','zloty','zonal',
]


// 정답 후보는 아니지만 추측으로 허용되는 단어 (Wordle 전략어, 일반 영단어)
const EXTRA_GUESSES: string[] = [
  // 인기 Wordle 오프너 / 전략어
  'crane','slate','stare','adieu','audio','tears','tares','rates','saner','earns',
  'cares','acres','cadre','renal','arise','aeons','irone','elate','rosin','oater',
  'raile','soare','caret','carte','cater','trace','react','crate','eclat','recta',
  // 일반 명사·형용사·동사 추가
  'abaft','abase','abash','abate','abeam','abets','abuzz','acids','acmes','acnes',
  'acock','acorn','acres','actin','adays','adeem','adeps','adust','aerie','affix',
  'again','agism','agist','aglet','agnus','agone','agons','agora','ahold','aided',
  'aimer','aired','airts','aitch','aiver','alack','alamo','alans','alate',
  'albas','algae','algal','alias','allay','aloft','aloud','alums','alure','amass',
  'ambit','amice','amide','amine','amins','amirs','amiss','ample','andro','anear',
  'anime','anils','anion','anise','anoas','anole','antae','antes','antic',
  'apers','aphid','aport','apres','aptly','arced','argle','ariel','arils','ariot',
  'arise','arles','armet','arpen','arras','arses','arsis','arson','asana','ascii',
  'ashen','ashed','ashes','asker','aspic','assay','asses','atilt','atilt','atoms',
  'atone','atony','atopy','attic','audio','audit','aught','aurar','aures','auris',
  'avian','avion','avows','axial','axile','axils','axion','ayahs',
  // B 추가
  'babel','babes','bacon','badge','bails','baits','baize','baled','baler','bales',
  'balky','bands','banes','bangs','banjo','banks','barbs','bards','barer','bares',
  'barfs','barge','barmy','barns','baron','basal','based','bases','baste','batik',
  'baton','bayou','beads','beaks','beams','beans','beaut','beefs','beers','beets',
  'beige','belle','bells','belts','bends','betas','bidet','bides','biers','binds',
  'bines','binge','biros','bites','bitsy','biway','blahs','bland','blank','blare',
  'bless','blimp','blobs','blogs','bloke','boars','bodes','bogus','bolts','bonds',
  'boner','bones','bongs','books','booms','boons','boots','boozy','borer','botch',
  'botox','bosom','brads','brags','brake','brand','brans','brash','brays','braze',
  'broke','brood','broth','brute','bucks','buffs','buggy','bulls','bumps','bunny',
  'burns','burps','burro','busts','butts','buxom','bylaw',
  // C 추가
  'cache','cameo','camos','camps','caned','caner','canes','caped','caper','capes',
  'carbs','cards','carve','cased','cases','catty','cauld','caves','cease','ceded',
  'cedes','cello','ceres','chafe','chain','chaps','chats','chaws','chide',
  'chips','chops','chord','chose','chump','chuck','chugs','chute','cited','citer',
  'cites','civvy','clack','clads','clads','clags','clams','claps','clash','clays',
  'clops','clots','clovs','clown','clubs','clues','coats','cobbs','cobra',
  'coded','coder','codes','coifs','coils','coins','coked','cokes','colds','comet',
  'comes','combs','condo','cones','conks','coops','coped','copes','copse','corns',
  'costs','coups','coven','cowed','cower','coxed','coxes','coyed','cozen','crabs',
  'crack','craft','crags','crams','craps','crave','craws','creek','crepe','crews',
  'crick','crisp','crits','croak','crocs','crone','croon','crops','croup','crows',
  'crump','cuffs','culls','culpa','curds','cured','cures','curfs','curry',
  'cusps','cysts',
  // D 추가
  'dated','dater','dates','daubs','dawns','dazed','daces','deals','deans','deeds',
  'deems','deeps','deets','defer','deign','dells','dense','dents','depot','derms',
  'desks','deter','diked','dikes','dills','dimes','diode','dirge','discs',
  'disks','ditty','dived','diver','dives','dixie','doers','doily','doled','doles',
  'dolls','dolts','domed','domes','dopes','dorks','dotes','doted','doter','dotes',
  'dotty','doves','dowdy','dowel','downs','doyen','drabs','drags','drake','drams',
  'drape','drawl','drawn','drays','dregs','drest','droit','drool','drops','drove',
  'drubs','drumm','drusy','duels','duets','dulls','dumps','dunce','dunes','dunno',
  'duped','duper','dupes','duple','durst',
  // E 추가
  'eased','easel','eases','easts','eaten','eater','ebbed','edges','edged','edger',
  'egged','egger','egads','elide','elint','elope','embay','emend','emote',
  'emyde','endue','enema','ensue','enter','erode','erred','essay','ether','evoke',
  'exact','exalt','excel','exert','exude','exult','eyrie',
  // F 추加
  'fable','faced','facer','faces','faked','faker','fakes','famed','fanes','fangs',
  'farms','fated','fates','fazed','fazed','feign','fells','felts','fends','feral',
  'ferny','feted','fetes','fiend','fifer','figue','filar','filed','filer',
  'files','fills','filth','finds','fired','firer','fires','firms','fishy','fists',
  'fjord','flack','flags','flail','flair','flake','flaky','flaps','flare','flats',
  'flaws','fleas','fleck','flees','flick','flied','flies','fling','flint','flips',
  'flirt','floes','flogs','flood','flops','floss','flows','flown','flubs','fluff',
  'fluke','flung','flunk','flute','flyer','foams','foamy','foils','folds','folic',
  'fomit','fonds','foods','fools','foray','fords','forms','forts','foxes','foyer',
  'foyer','franc','frees','freer','fresh','frets','fritz','frogs','froze','fudge',
  'fugue','fumes','fungi','funky','furls','furor','fused','fuses','fussy',
  // G 추가
  'gaffs','gaily','gains','gaits','gamut','gangs','garbs','garbs','gases','gasps',
  'gaudy','gauge','gauze','gaunt','gauze','gavel','gazer','gazes','gears','geese',
  'gelid','germs','gibed','gibes','gilds','giron','girts','gists','glads','glare',
  'glean','glees','glide','glint','gloat','globs','gloop','gloss','glued',
  'glues','gnash','gnaws','goers','golfs','goofs','gorge','gorge','gouge','graft',
  'grain','gramp','grans','grasp','grays','graze','greed','greet','greys','grime',
  'grimy','grins','gripe','grips','grist','grits','groan','grope','gross','grout',
  'grubs','gruel','gruff','grump','grunt','guava','gulch','gulls','gumbo','gunky',
  'gusts','gutsy',
  // H 추가
  'haiku','hairs','hairy','handy','hangs','hardy','harms','haven','heads','heady',
  'heaps','hears','heave','hefty','helix','helms','hence','heron','hijab','hilly',
  'hippo','hippy','hoary','hoick','holds','holes','holly','homes','honey','hooks',
  'hoops','horns','hover','howdy','humid','hunks','hunky','hurls',
  // I 추가
  'icily','icing','icons','idiom','idiot','idler','idles','igloo','imams','incur',
  'inept','infix','ingot','inlet','inter','intro','ionic','irons','islet',
  'itchy',
  // J 추가
  'jaded','jails','jakes','japes','jazzy','jeers','jibed','jibes',
  'jibed','jiffy','jingo','jived','jiver','jives','joust','jokey','jolts','jones',
  'joule','joust','jubas','jumps','junky','junto',
  // K 추가
  'kayak','kazoo','keeps','keels','keens','kelps','khaki','knack','knave','knead',
  'kneel','knelt','knobs','knots',
  // L 추가
  'labia','laden','ladle','lamps','lands','lanes','lapel','lapse','larch','laved',
  'laves','lawns','leafy','leapt','letch','lifer','lifts','limes','limps','lingo',
  'links','lisle','lists','loans','loamy','loans','lobby','lofty','looms','loops',
'loopy','lorry','loupe','lousy','lumps','lumpy','lunch','lungs','lying',
  // M 추가
  'maize','males','mambo','manes','mangy','mania','manly','manor','manse',
  'march','mares','marks','masse','masts','mated','mates','matey','mauds','mawed',
  'maxim','mazes','melds','mends','messy','meted','middy','miffs','milky','mills',
  'mimed','mimes','mimic','mince','mired','mires','misty','mitts','moles','monks',
  'monky','mocha','mocks','modes','moils','moist','moldy','molts','monks','moose',
  'moped','morph','mossy','motif','moult','mucky','mulls','mural','musts','mythy',
  // N 추가
  'narco','narcs','needy','newts','nicer','nicks','nippy','nitty','nixed','nixie',
  'nodal','nodes','nooks','norms','norsk','notch','nudge',
  // O 추가
'oaken','oaves','obese','obeys','oboes','ombre','onset','opted','optic',
  'orate','outer','ovary','ovoid','owing','oxide',
  // P 추가
  'paced','pacer','paces','packs','paddy','palls','palms','pants','pared','pares',
  'parks','parse','parts','paved','paver','paves','peaks','pears','peeks','peels',
  'peers','peeve','pelts','pends','peppy','perms','pesky','petri','picks','picky',
  'pints','pions','pipes','pipit','pithy','plait','plank','plans','plash','plasm',
  'plats','plumb','plume','plums','plunk','poise','poles','poled','poler','polka',
  'poops','poses','posts','potty','pouty','preys','price','pricy','primp','prink',
  'privy','prong','props','prosy','prowl','proxy','psalm','pudgy','puffs','puffy',
  'pumps','punks','punts','puppy','purrs','pushy',
  // R 추가
  'rabid','raids','rails','raked','raker','rakes','rants','raved','raver','raves',
  'reams','reaps','rebus','recto','reedy','reeks','reeve','reign','reins','relax',
  'relay','relic','remit','rends','rents','repay','repel','reran','rerun','rests',
  'rides','rills','rinds','risen','rites','roams','robed','robes','ropes','roses',
  'roils','rooks','rooms','roost','routs','roved','rover','roves','ruddy','ruffs',
  'ruins','rulls','rumen','runes','rungs','runny','runts','rusks','rusts',
  // S 추가
  'sagas','sages','saggy','salve','salvo','sandy','sappy','sards','sated','saucy',
  'scale','scans','scarf','scarp','scary','scats','scoff','scold','scone','scoop',
  'scoot','scops','scorn','scots','scour','scowl','scram','scrod','scrum','seams',
  'seeps','seize','semen','sends','serfs','shack','shads','shaft','shags',
  'shaky','shams','shank','shiny','shire','shirk','shoal','shoes','shoon','shops',
  'shots','shout','shove','shows','shuld','sided','sides','sieve','sigma','signs',
  'silex','silks','silky','sills','silts','simps','sinew','sings','sinks','sinky',
  'sippy','sites','sixte','sizes','skied','skier','skies','skimp','skips','skulk',
  'skull','slabs','slake','slaps','slats','slays','slick','sling','slips',
  'slits','slimy','slung','slunk','slurp','slurs','smack','smash','smear','smell',
  'smelt','smock','smogs','smote','snobs','snoop','snoot','snuck','snuff','soaks',
  'soaps','soapy','socks','sofas','softy','soils','souls','soups','soupy','spade',
  'spams','spank','spars','spats','specs','speed','speel','spelt','spend','spews',
  'spics','spied','spiel','spies','spiff','spiky','spins','splay','spool','spots',
  'spout','sprig','spunk','spurn','stabs','stags','stagy','stays','stems',
  'steps','stern','sties','sting','stink','stint','stirs','stoic','stomp','strap',
  'strop','suave','suede','sulky','sully','sumps','sunup','surly','sushi','sways',
  'swigs','swill','swims','swine','synth',
  // T 추가
  'tabes','tabor','talky','tamps','tango','tapas','taped','taper','tapes','tarns',
  'tarps','tarry','tatty','taxed','taxer','taxes','taxis','teaks','teams',
  'teems','teens','teeny','teeny','tempo','temps','tends','tenon','tents','tepee',
  'terms','terns','tests','techy','thews','thole','tibia','tiffs','tills','tilts',
  'tipsy','toads','toffs','toffy','tolls','tonal','toner','tones','towns','toxic',
  'toxic','toyed','trabs','tragi','tramp','traps','trawl','trays','trees','tress',
  'trews','trice','trims','trips','trois','troll','troth','trots','trout',
  'trued','truer','trues','trump','tsars','tuber','tubes','tufts','tumid',
  'turfs','turvy','tusks','tutus','tuxes','twigs','twine','twins','twits',
  // U 추가
  'ulnar','unarm','unbar','uncap','uncut','unfit','unify','unity','unlit','untie',
  'unwed','upped','using',
  // V 추가
  'vague','venal','vexed','vexes','vices','video','vigil','vireo','visor','vogue',
  'voile','volts','vying',
  // W 추가
  'waded','wader','wades','waged','wager','wages','wagon','waifs','waive','walks',
  'wants','wards','warns','warps','waxed','waxen','waxes','weeds','weeks','weeps',
  'weepy','welts','whims','whine','whiny','whips','wires','woken','wolfs',
  'words','wordy','wring','woken','yanks','yarns','yeahs','yells','yelps','yipes',
  'yodel','yolks',
  // Z 추가
  'zappy','zincs','zingy','zones',
]

// NYT Wordle 공개 유효 단어 목록 (출처: github.com/kcwhite)
const NYT_VALID: string[] = [
  // A
  'aahed','abaft','abate','abaya','abele','abets','abuzz','ached','aches','achoo',
  'acned','acned','acted','actin','adieu','adios','aeons','afoot','afore','afrit',
  'aglee','aglet','ahold','aioli','airts','aitch','aided','aider','aides','aldol',
  'algae','algal','alibi','allee','almah','almas','almeh','aloes','aloha','altho',
  'alula','alvar','amahs','amain','ambit','ambos','ameba','ameen','amens','ament',
  'amide','amido','amids','amies','amiga','amigo','amine','amino','amirs','amoks',
  'amort','amour','amped','anana','ancho','anear','anele','angas','anigh','anile',
  'anils','anima','anker','ankus','anlas','annas','annat','anoas','anole','antar',
  'anted','anura','anyon','apace','apert','apian','apish','apode','apods','aport',
  'appal','appui','apres','apses','apsis','apted','apter','aquae','aquas','ardeb',
  'aread','areae','areas','areca','arene','arepa','arhat','ariki','arils','arked',
  'arled','arles','armet','armil','arnut','aroha','aroid','arpen','arras','arris',
  'arsed','artal','artel','arval','asdic','ashed','ashet','askoi','aspis','assay',
  'aster','astir','atilt','atman','atmas','atocs','atomy','atony','atopy','atria',
  'attap','attar','audad','auger','aulic','auloi','aulos','aurae','aural','aurei',
  'auric','auxin','avant','avast','avens','avers','avgas','avian','avion','avise',
  'avize','avows','axile','axils','axite','axled','axman','axmen','axoid','axone',
  'axons','azide','azine','azole','azote','azoth','azyms',
  // B
  'babka','baboo','babul','baccy','bacha','baddy','bairn','baize','baldy','baled',
  'balks','bally','balms','baloo','balsa','balti','banda','bandy','bania','banns',
  'barfi','barfs','baric','barky','barms','barmy','barra','barre','bason','bassi',
  'basso','basta','bauds','baulk','bavin','bawks','bazar','beamy','beano','beany',
  'beaus','beaux','bebop','bedad','bedim','beedi','begad','begar','beige','bekah',
  'belah','belar','belga','belon','bemad','benga','benis','benne','benni','bento',
  'berks','berme','berms','berob','beryl','besom','besot','beton','betta','bever',
  'bevor','bevvy','bhaji','bhang','bhoot','bhuna','biffo','biffs','biffy','bifid',
  'bigha','bight','bijou','bikie','bilbo','bilby','bilgy','bilks','bimbo','bindi',
  'bings','bints','biogs','biont','biota','biped','bipod','birle','birls','birse',
  'bisom','bitsy','bitte','bitts','bizzo','blads','blaes','blaff','blahs','blain',
  'blase','blash','blate','blats','blebs','blech','bling','blini','blins','blips',
  'blobs','blocs','blogs','bloop','blore','blubs','bluet','bluey','bluid','blume',
  'blunk','blype','boaks','boded','bodes','bodge','bodhi','bodle','boffo','boffs',
  'bogan','boggy','bogie','bogle','bogue','bohea','bohos','boink','boite','bokeh',
  'bolls','bolos','bolus','bombe','bombo','bonce','boned','boner','bongs','bonie',
  'bonks','bonne','bonny','bonza','bonze','boobs','boody','boofy','bools','boong',
  'boord','boors','boose','boppy','borak','borde','bords','boree','borel','borgo',
  'borms','borts','bosie','bosks','bosky','boson','bosun','bothy','botte','botts',
  'botty','bouge','bouks','boult','bouns','bourd','bourg','bourn','bouse','bousy',
  'bovid','bowie','bowne','bowrs','boxen','boxty','boyar','boyau','bozos','braai',
  'brach','brack','bract','brads','braes','brame','brane','brank','brans','brant',
  'brast','brava','bravi','braws','braxy','braza','brede','breds','breem','breer',
  'brees','breid','breis','breme','brens','brent','brere','brers','breve','breys',
  'brier','bries','brigs','brill','brins','brios','brise','briss','brith','brits',
  'britt','brize','broch','brock','brods','brogs','brome','bromo','bronc','brond',
  'brool','broos','brose','brosy','brugh','bruin','bruit','brule','brume','brung',
  'brusk','brust','bruts','bubba','bubbe','bubby','buchu','bucko','budos','buffa',
  'buffe','buffi','buffo','buffy','buhls','buhrs','buist','bukes','bulla','bumbo',
  'bumfs','bumph','bunco','bunds','bundt','bundu','bundy','bungy','bunje','bunko',
  'bunns','bunty','bunya','buran','buras','burbs','burds','buret','burfi','burgs',
  'burin','burka','burke','burks','buroo','burqa','bursa','burse','busby','busks',
  'busky','busti','buteo','butes','butle','butoh','butty','butut','butyl','bwana',
  // C
  'cabas','caber','cabob','caboc','cabre','cacas','cacks','cacky','cadee','cades',
  'cadge','cadgy','cadie','caeca','caese','caffs','caged','cager','cahow','caids',
  'caird','cajon','cajun','caked','cakey','calfs','calid','calif','calix','calks',
  'calla','calmy','calos','calpa','calps','calve','calyx','caman','camas','cames',
  'camis','campi','campo','campy','camus','caneh','caner','cangs','canid','canna',
  'canns','canso','canst','canto','capas','capex','caphs','capiz','caple','capon',
  'capos','capot','capri','capul','carap','carbo','carby','cardi','cared','carer',
  'caret','carex','carks','carle','carls','carns','carny','carom','caron','carpi',
  'carrs','carta','carvy','casas','casco','cased','casks','casky','casus','cauda',
  'cauks','cauld','cauls','caums','caups','cauri','causa','cavas','cavel','caver',
  'cavie','cawks','caxon','ceaze','cebid','cecal','cecum','ceded','ceder','cedis',
  'ceiba','ceili','ceils','celeb','celli','celom','cento','cents','ceorl','cepes',
  'cerci','cered','ceres','cerge','ceria','ceric','cerne','ceroc','ceros','certy',
  'cesse','cesta','cesti','cetes','cetyl','cezve','chace','chack','chaco','chado',
  'chads','chaft','chais','chals','chams','chana','chank','chape','chapt','chara',
  'chare','chark','charr','chary','chave','chavs','chawk','chaya','chays','cheep',
  'cheka','chela','chelp','chemo','chere','chert','cheth','chevy','chewy','chiao',
  'chias','chibs','chich','chico','chiel','chiks','chimb','chimo','chine','chink',
  'chino','chirk','chirl','chirm','chirr','chirt','chiru','chive','chivs','chivy',
  'chizz','choco','chocs','chode','chogs','choil','choko','choky','chola','choli',
  'cholo','chons','choof','chook','choom','choon','chota','chott','chout','choux',
  'chowk','chubs','chufa','chuff','churl','churr','chuse','chuts','chyle','chyme',
  'cibol','ciels','ciggy','cills','cimar','cimex','cinct','cinqs','cippi','circs',
  'cires','cirls','cirri','cisco','cists','cital','cited','cives','civet','civie',
  'civvy','clach','clads','claes','clags','clame','clans','clapt','claro','clart',
  'clast','clats','claut','clavi','cleck','cleek','cleep','clegs','cleik','clems',
  'clepe','clept','cleve','clews','clied','clift','clime','cline','clint','clipe',
  'clips','clipt','clits','cloam','cloff','cloke','clomb','clomp','clonk','clons',
  'cloop','cloot','clote','clour','clous','clows','cloye','cloys','cloze','cluey',
  'clunk','clype','coact','coady','coala','coaly','coapt','coarb','coati','cobbs',
  'cobby','cobia','coble','cobza','cocas','cocci','cocco','cocks','cocos','codec',
  'coden','codex','codon','coeds','coffs','cogie','cogon','cogue','cohab','cohen',
  'cohoe','cohog','cohos','coign','coirs','coits','colas','colby','coled','coley',
  'colin','colls','colly','colog','colza','comae','comal','combe','combi','commo',
  'commy','compo','compt','comte','comus','coney','confs','conga','conge','congo',
  'conia','conin','conks','conky','conne','conns','conte','conto','conus','convo',
  'cooch','cooee','cooer','cooey','coofs','cooky','coomb','cooms','coomy','coops',
  'coopt','coost','cooze','copal','copay','copen','coppy','copra','copsy','coqui',
  'coram','corbe','corby','cored','corey','corgi','corks','corni','corno','cornu',
  'corse','corso','cosec','cosed','coset','cosey','cosie','coste','cotan','coted',
  'cotes','coths','cotta','cotts','coude','courb','courd','coure','couta','coved',
  'covin','cowal','cowan','cowks','cowls','cowps','cowry','coxae','coxal','coxed',
  'coxes','coxib','coyau','coyed','coyer','coypu','cozed','cozen','cozes','cozey',
  'cozie',
  // D
  'daals','dabba','daces','dacha','dacks','dadah','dadas','daffs','daffy','dagga',
  'daggy','dagos','dahls','daiko','daine','daint','daker','daled','dales','dalis',
  'dalle','dalts','daman','damar','damme','damns','damps','dampy','dancy','dangs',
  'danio','danks','danny','dants','daraf','darbs','darcy','darga','dargs','daric',
  'daris','darky','darns','darre','darzi','dashi','dashy','datal','daube','dauby',
  'dauds','dault','dauts','daven','davit','dawds','dawen','dawts','dayan','daych',
  'dazer','dazes','deair','deare','dearn','deash','deave','deaws','deawy','debag',
  'debby','debel','debes','debud','debur','debus','debye','decad','decaf','decko',
  'decos','dedal','deedy','deely','deems','deene','deere','deeve','deevs','defat',
  'deffo','defis','defog','degas','degum','degus','deice','deids','deils','deked',
  'dekes','dekko','deled','deles','delfs','delft','dells','delly','delos','delph',
  'deman','demes','demic','demit','demob','demoi','dempt','denar','denay','dench',
  'denet','denis','deoxy','derat','deray','dered','deres','derig','derma','derms',
  'derns','derny','deros','derro','derry','derth','dervs','desex','deshi','desis',
  'desse','devas','devel','devis','devon','devos','devot','dewan','dewax','dexes',
  'dexie','dilly','diked','dikes','dinos','dirge','discs','ditty','dived','diver',
  'dives','doers','doily','domed','dopes','dorks','doted','doter','dovey','doyen',
  'drabs','drags','drake','drams','drape','drawl','drays','dregs','droit','drool',
  'drops','drubs','duels','duets','dulls','dunce','dunes','dunno','duped','duper',
  // E
  'eards','earns','earnt','earst','eased','easer','easle','eathe','eaved','eaves',
  'ebbed','ebons','ecads','eched','eches','echos','edged','edger','edile','educe',
  'educt','eejit','eensy','effed','egads','egers','egest','eggar','egger','ehing',
  'eider','eidos','eigne','eiked','eikon','eilds','eisel','ejido','ekkas','elain',
  'eland','elans','elchi','eldin','elemi','elfed','eliad','elint','elmen','eloge',
  'elogy','eloin','elops','elpee','elsin','elute','elvan','elven','elver','emacs',
  'embar','embay','embog','embow','embox','embus','emeer','emerg','emery','emeus',
  'emics','emmas','emmer','emmet','emmew','emoji','emong','emove','empts','emule',
  'emure','emyde','emyds','enarm','enate','endew','enews','enfix','enlit','enmew',
  'ennog','enoki','enols','enorm','enows','enrol','ensew','ensky','entia','enure',
  'enurn','enzym','eorls','eosin','epact','epees','ephah','ephas','ephod','ephor',
  'epode','epopt','epris','equid','erbia','erevs','ergon','ergos','erhus','erica',
  'erick','ering','erned','ernes','erred','eruct','erugo','eruvs','erven','ervil',
  'escar','escot','esile','eskar','esker','esnes','estoc','estop','estro','etage',
  'etape','etats','etens','ethal','ethne','etics','etnas','ettin','ettle','etuis',
  'etwee','etyma','eughs','euked','euros','eusol','evens','evert','evets','evite',
  'ewers','ewest','ewhow','exeat','execs','exeem','exeme','exies','exine','exode',
  'exome','exons','expat','expos','exuls','exurb','eyass','eyers','eyots','eyras',
  'eyres','eyrie','eyrir','ezine',
  // F
  'fabby','faced','facer','facia','facta','faddy','fader','fadge','fados','faena',
  'faery','faffs','faffy','faggy','fagin','fagot','faiks','faine','faired','faker',
  'fakey','fakie','fakir','falaj','famed','fanal','fands','fanes','fanga','fango',
  'fanks','fanon','fanos','fanum','faqir','farad','farci','farcy','fards','farer',
  'farle','farls','faros','farro','farse','fasci','fasti','fatly','fatso','fatwa',
  'faugh','fauld','fauns','fauts','fauve','favas','favel','faver','favus','fawns',
  'fawny','fayed','fayer','fayne','fayre','fazed','fazes','feals','feare','feart',
  'fease','feaze','fecht','fecit','fecks','feebs','feens','feers','feese','feeze',
  'fehme','feint','feist','felch','felid','fells','felly','femal','femes','femmy',
  'fendy','fenis','fenks','fenny','fents','feods','feoff','ferer','feria','ferly',
  'fermi','ferms','fesse','festa','fetas','feted','fetor','fetta','fetts','fetwa',
  'feuar','feuds','feued','feyed','feyer','feyly','fezes','fezzy','fiars','fiats',
  'fibre','fibro','fiche','fichu','ficin','fides','fidge','fidos','fiefs','fient',
  'fiere','fiers','fifed','fifer','fifis','figgy','figos','fiked','fikes','filch',
  'filii','filks','fille','fillo','filmi','filum','finca','fined','finis','finks',
  'finny','finos','fiord','fired','firer','firie','firns','firry','fiscs','fisks',
  'fisty','fitch','fitna','fitte','fitts','fiver','fixit','fjeld','flaff','flags',
  'flaks','flamm','flams','flamy','flane','flans','flary','flava','flawn','flawy',
  'flaxy','fleam','fleas','fleek','fleer','flees','flegs','fleme','fleur','flews',
  'flexi','flexo','fleys','flics','flimp','flims','flirs','flisk','flite','flits',
  'flitt','flocs','floes','flogs','flong','flors','flory','flosh','flota','flubs',
  'flued','flues','fluey','fluky','flump','fluor','flurr','fluty','fluyt','flyby',
  'flype','flyte','foamy','foehn','fogey','fogie','fogle','fogou','fohns','foids',
  'foils','foins','foley','folia','folie','folky','fomes','fonda','fonds','fondu',
  'fones','fonly','foody','foram','forbs','forby','fordo','fords','forel','fores',
  'forex','forky','forme','forza','forze','fossa','fosse','fouds','fouer','fouet',
  'foule','fouth','fovea','fowth','foxie','foyle','foyne','frabs','frack','fract',
  'frags','fraim','franc','frape','fraps','frass','frate','frati','fraus','freet',
  'freit','fremd','frena','frere','fribs','frier','frigs','frise','frist','frith',
  'frits','fritt','frize','frizz','froes','frons','frore','frorn','frory','frows',
  'frugs','frump','frush','frust','fubar','fubby','fubsy','fucus','fudgy','fuero',
  'fuffs','fuffy','fugal','fuggy','fugie','fugio','fugle','fugly','fujis','fumed',
  'fumer','fumet','fundi','fungy','fural','furan','furca','furol','furrs','furth',
  'furze','furzy','fusee','fusel','fusil','fusks','fusts','fusty','fuzed','fuzee',
  'fuzes','fuzil','fyces','fyked','fykes','fyles','fyrds',
  // G
  'gaped','gaper','gapes','gappy','garbe','garbo','garbs','garda','gares','garic',
  'garis','garms','garni','garre','garth','garum','gasps','gaspy','gasts','gatch',
  'gated','gater','gaths','gator','gauch','gaucy','gauds','gauje','gault','gaumy',
  'gaups','gauss','gauzy','gavot','gawds','gawks','gawps','gawsy','gayal','gazal',
  'gazar','gazer','gazes','gazon','gazoo','geese','gelid','germs','gibed','gibes',
  'gilds','girts','gists','glads','glean','glees','glide','glint','gloat','globs',
  'gloop','glower','glued','glues','gnash','gnaws','golfs','goofs','gorge','gouge',
  'graft','gramp','grans','graze','greys','grime','grimy','grins','gripe','grips',
  'grist','grits','grope','grout','grubs','gruel','gruff','grump','grunt','guava',
  'gulch','gulls','gumbo','gusts','gutsy',
  // H
  'haiku','hairs','hairy','handy','hangs','hardy','harms','heads','heady','heaps',
  'heave','hefty','helix','helms','hence','heron','hijab','hilly','hippo','hippy',
  'hoary','holds','holes','holly','homes','honey','hooks','hoops','horns','hover',
  'howdy','humid','hunks','hunky','hurls',
  // I
  'icily','icing','icons','idiom','idiot','idler','idles','igloo','imams','incur',
  'inept','infix','ingot','ionic','irons','islet','itchy',
  // J
  'jaded','jails','jakes','japes','jazzy','jeers','jibed','jibes','jiffy','jingo',
  'jinks','jived','jiver','jives','joust','jolts','joule','jumps','junky','junto',
  // K
  'kayak','kazoo','keeps','keels','keens','kelps','khaki','knack','knave','knead',
  'knelt','knobs','knots',
  // L
  'labia','laden','ladle','lamps','lands','lanes','lapel','lapse','larch','leafy',
  'leapt','letch','lifer','lifts','limes','limps','lingo','links','lisle','lists',
  'loans','loamy','lobby','lofty','looms','loops','loopy','lorry','loupe','lousy',
  'lumps','lumpy','lunch','lungs',
  // M
  'maize','mambo','mangy','mania','manly','manse','marks','masse','masts','matey',
  'mauds','mauls','maund','mauri','maxes','maxis','mazed','mazes','melds','mends',
  'messy','meted','middy','miffs','milky','mills','mimed','mimes','mimic','mired',
  'mires','misty','mitts','moles','monks','mocha','mocks','modes','moist','moldy',
  'molts','moose','moped','morph','mossy','motif','moult','mucky','mulls','mural',
  'musts',
  // N
  'narco','narcs','natch','nates','natty','navar','naves','navvy','nawab','nazes',
  'neddy','needy','neeps','nerds','nervy','nests','netty','newel','newts','nexus',
  'niche','nidus','niffy','nifty','nighs','ninth','nitro','nitty','nixed','nixie',
  'nizam','nodal','noddy','nodes','noels','noggs','noils','noirs','nooks','nooky',
  'noons','nopal','noria','noris','norma','nosed','noser','noter','notum',
  'nudge','nudie','nukes','nulls','numen',
  // O
  'oaken','oakum','oases','oasis','oasts','oaten','oaths','obeah','obeys','oboes',
  'occur','ocher','ochre','ocker','octet','odder','oddly','odeum','odour','ofays',
  'ogham','ogled','ogler','ogles','ohmic','oinks','okapi','okays','okras','oldie',
  'oleic','olein','oleos','oleum','omens','omits','oomph','ooped','oorie','oozed',
  'oozes','opahs','opals','opsin','oracy','orant','orbed','orcas','orcin','oread',
  'oriel','orles','ormer','ornis','orpin','orris','ortho','oscar','osier','ostia',
  'ottar','ouens','oundy','ousel','outdo','outre','outro','ouzel','ouzos','ovels',
  'overt','ovist','ovoli','ovolo','ovule','oxbow','oxeye','oxids','oxime','oxlip',
  'oxter',
  // P
  'pacas','paced','pacer','pacey','pacha','pacos','padis','padre','padri','paean',
  'paedo','paeon','paged','pager','pagle','pagod','pagri','paisa','pakka','palay',
  'palea','paled','palet','palis','palki','palls','palpi','palps','pampa','panax',
  'pance','pands','pandy','panga','panim','panko','panne','panni','panty','paoli',
  'papas','papaw','papes','pappi','pappy','parae','pardi','pards','paren','pareo',
  'pareu','parev','parge','pargo','parki','parky','parle','parly','parma','parol',
  'parps','parra','parti','parve','parvo','paseo','pasha','pashm','paska','passe',
  'paten','paths','patin','patka','patly','patte','pauas','pavan','paved','paven',
  'pavid','pavin','pavis','pawas','pawaw','pawks','pawky','paxes','peage','peags',
  'peaks','peaky','peals','peans','peare','peart','pease','peaty','peavy','peaze',
  'pechs','pecke','pecky','pedes','pedis','pedro','peece','peens','peeoy','peepe',
  'peery','peeve','peggy','peins','peise','peize','pekan','pekes','pekin','pekoe',
  'pelas','pelau','peles','pelfs','pells','pelma','pelon','pelta','pendu','pened',
  'penes','pengo','penie','penks','penna','penni','peons','pepla','pepos','pepsy',
  'perai','perce','percs','perdu','perdy','perea','peris','perns','perog','perps',
  'perse','perst','perve','pervo','pervs','pervy','petar','petit','petre','petri',
  'petti','petto','pewee','pewit','peyse','phage','phang','phare','pharm','phene',
  'pheon','phese','phial','phizz','phlox','phono','phots','phuts','phyla','phyle',
  'pibal','pical','picas','piccy','picot','picra','picul','piend','piert','pieta',
  'piets','piezo','pight','pigmy','pikas','piked','piker','pikes','pikey','pikis',
  'pikul','pilaf','pilao','pilau','pilaw','pilch','pilea','pilei','pilis','pilow',
  'pilum','pilus','pimas','pinas','pingo','pinko','pinna','pinny','pinon','pinot',
  'pinta','pinup','piony','pious','pioye','pioys','pipal','pipas','pipet','pipis',
  'pipit','pippy','pipul','pirai','pirls','pirns','pirog','pisco','pisky','pisos',
  'pissy','piste','piths','piton','pitot','pitta','piums','pized','pizes','plaas',
  'plack','plage','plaps','plash','plasm','plats','platt','playa','plebe','plebs',
  'plena','pleon','plesh','plews','plica','plims','pling','plink','ploat','plods',
  'plong','plook','plops','plotz','plouk','ploye','plues','pluff','plugs','plums',
  'pluot','plyer','poaka','poake','poboy','pocks','pocky','podal','poddy','podge',
  'podgy','podia','poeps','pogey','pogge','poilu','poind','pokal','pokey','pokie',
  'polje','polks','polts','polys','pombe','pommy','pomos','pomps','poncy','ponds',
  'pones','poney','ponga','pongo','pongs','pongy','ponks','ponts','ponty','ponzu',
  'poods','poofs','poofy','poohs','pooja','pooka','pooks','poons','poopi','poori',
  'poort','poove','poovy','popes','poppa','popsy','porae','poral','pored','porer',
  'porge','porgy','porin','porks','porno','porns','porny','porta','porty','posed',
  'posey','posho','potae','potch','poted','potes','potin','potoo','potsy','potto',
  'potts','pouff','poufs','pouke','pouks','poule','poulp','poupe','poupt','powan',
  'powin','pownd','powns','powny','powre','poxed','pozzy','praam','prads','prahu',
  'prana','praos','prase','prate','pratt','praty','praus','predy','preed','prees',
  'preif','prems','premy','prent','preon','preop','presa','prese','prest','preve',
  'prexy','prial','prief','prier','prigs','prill','prima','primp','primy','prion',
  'priss','proas','prods','proem','profs','progs','proin','proke','prole','proll',
  'prono','prore','proso','pross','proto','proul','proyn','prunt','pryer','pryse',
  'pseud','psoae','psoai','psoas','psora','psyop','pubco','pubes','pubis','pucan',
  'pucer','puces','pucka','puddy','pudge','pudic','pudor','pudsy','pudus','puers',
  'puffa','puggy','pugil','pujah','pujas','pukas','puked','puker','pukes','pukey',
  'pukka','pukus','pulao','pulas','puled','puler','pulik','pulis','pulka','pulks',
  'pulli','pully','pulmo','pulus','pumie','punas','punce','punga','pungs','punji',
  'punka','punky','punny','punto','punts','punty','pupae','pupas','pupus','purda',
  'pured','pures','purin','purls','purpy','purrs','pursy','purty','puses','pusle',
  'putid','puton','putti','putto','puzel','pyats','pyets','pygal','pyins','pyned',
  'pynes','pyoid','pyots','pyral','pyran','pyres','pyric','pyros','pyxie','pyxis',
  // Q
  'qadis','qaids','qanat','qibla','quaff','quags','quair','quaky','quant','quare',
  'quass','quate','quats','qubit','quean','queme','quena','quern','queys','quids',
  'quiff','quina','quine','quino','quino','quipo','quipu','quire','quirt','quist',
  'quoad','quods','quoif','quoin','quoit','quoll','quonk','quops','qursh','quyte',
  // R
  'rabat','rabic','rabis','raced','rache','racon','radge','radix','radon','raffs',
  'rafts','ragas','raged','ragee','rager','ragga','raggs','raggy','ragis','ragus',
  'rahui','raias','raids','raiks','raile','raine','raird','raita','raits','rajas',
  'rajes','raked','rakee','raker','rakes','rakia','rakis','rakus','rales','ramal',
  'ramee','ramet','ramie','ramin','ramis','rammy','ramps','ramus','ranas','rance',
  'rands','ranee','ranga','rangi','rangs','rangy','ranid','ranis','ranke','ranks',
  'raped','raper','rapes','raphe','rappe','rarks','rased','raser','rases','rasps',
  'rasse','ratal','ratan','ratas','ratch','ratel','ratha','rathe','raths','ratoo',
  'ratos','ratus','rauns','raupo','raved','ravel','ravey','ravin','rawer','rawin',
  'rawns','rayah','rayas','rayed','rayle','rayne','razed','razee','razer','razoo',
  'readd','reads','reais','reaks','realo','reals','reame','reams','reamy','reans',
  'reast','reata','reate','reave','rebbe','rebec','rebid','rebit','rebop','rebuy',
  'recal','recce','recco','reccy','recit','recks','recon','recta','recti','recto',
  'redan','redds','reddy','reded','redes','redia','redid','redip','redly','redon',
  'redos','redox','redry','redub','redux','redye','reede','reefy','reeks','reeky',
  'reels','reens','reest','reeve','refed','refel','reffo','refis','refix','refly',
  'refry','regar','reges','reggo','regie','regma','regna','regos','regur','rehem',
  'reifs','reiki','reiks','reink','reird','reist','reive','rejig','rejon','reked',
  'rekes','rekey','relet','relie','relit','rello','reman','remap','remen','remet',
  'remex','remix','renay','rends','reney','renga','renig','renin','renne','renos',
  'rente','reoil','reorg','repeg','repin','repla','repot','repps','reran','rerig',
  'resaw','resay','resee','reses','resew','resid','resit','resod','resow','resty',
  'resus','retag','retax','retem','retia','retie','retox','revet','revie','rewan',
  'rewax','rewed','rewet','rewin','rewon','rewth','rezes','rheas','rheme','rheum',
  'rhies','rhime','rhody','rhone','rhumb','rhyne','rhyta','riads','rials','riant',
  'riata','ribas','ribby','ribes','riced','ricer','ricey','richt','ricin','ridgy',
  'ridic','riels','riems','rieve','rifer','rifte','rifts','rifty','riggs','rigol',
  'riley','rille','rimae','rimed','rimer','rimes','rimus','rindy','rines','rings',
  'rinks','rioja','riped','ripes','ripps','rises','rishi','risps','risus','ritts',
  'ritzy','rivas','rivel','riven','riyal','rizas','roams','roans','roars','roary',
  'roate','robed','robes','roble','roded','rodes','roguy','rohes','roids','roils',
  'roily','roins','roist','rojak','rojis','roked','roker','rokes','rolag','rolfs',
  'romal','romeo','ronde','rondo','roneo','rones','ronin','ronne','ronte','ronts',
  'roods','roofy','rooky','roons','roops','roopy','roosa','roose','rooty','roped',
  'roper','ropey','roque','roral','rores','roric','rorid','rorie','rorts','rorty',
  'roset','roshi','rosin','rosit','rosti','rosts','rotal','rotan','rotas','rotch',
  'roted','rotes','rotis','rotls','roton','rotos','rotte','roues','roule','rouls',
  'roums','roups','roupy','routh','roved','roven','rowan','rowel','rowen','rowie',
  'rowme','rownd','rowth','rowts','royne','royst','rozet','rozit','ruana','rubai',
  'rubby','rubel','rubes','rubin','ruble','rubli','rubus','ruche','rucks','rudas',
  'rudds','rudes','rudie','rudis','rueda','ruffe','ruffs','rugae','rugal','ruggy',
  'rukhs','rumal','rumbo','rumes','rumly','rumpo','rumpy','runch','runds','runed',
  'runic','runty','rupia','rurps','rurus','rusas','ruses','rusma','russe','ruths',
  'rutin','rutty','ryals','rybat','ryked','rykes','rynds','ryots',
  // S (most common additions)
  'saabs','sabal','safed','sagas','sagos','saheb','sahib','saice','saiga','saims',
  'saine','sairs','saist','saith','sajou','sakai','saker','sakia','sakis','sakti',
  'salal','salat','salep','salet','salic','salix','salle','salmi','salol','salop',
  'salpa','salps','salse','salto','salue','salut','saman','samas','sambo','samek',
  'samel','samen','samey','samfu','sammy','sampi','sands','saned','sanes','sanga',
  'sangh','sango','sangs','sanko','sansa','sants','saola','sapan','sapid','sapor',
  'saran','sards','sared','saree','sarge','sargo','sarin','sarks','sarky','sarod',
  'saros','saser','sasin','sasse','satai','satay','satem','satis','sauba','sauch',
  'saugh','sauls','sault','saunt','saury','sauts','savey','savin','sawah','sawer',
  'sayed','sayer','sayid','sayne','sayon','sayst','sazes','scabs','scads','scaff',
  'scags','scail','scala','scall','scand','scapa','scapi','scart','scath','scatt',
  'scaud','scaup','scaur','scaws','scena','schav','schmo','schul','sclim','scods',
  'scogs','scoog','scopa','scops','scoug','scoup','scowp','scrab','scrae','scran',
  'scrat','scraw','scrim','scrip','scrob','scrod','scrog','scrow','scudi','scudo',
  'scuds','scuff','scuft','scugs','sculk','sculp','sculs','scurf','scurs','scuta',
  'scute','scyes','seame','seams','seamy','seans','seare','sease','seaze','sebum',
  'secco','sechs','seder','sedes','sedge','sedgy','sedum','seeld','seels','seely',
  'seepy','sefer','segni','segno','segol','segos','sehri','seifs','seils','seine',
  'seirs','seise','seism','seity','seiza','sekos','sekts','selah','seles','sella',
  'selle','selva','semee','semes','semie','senas','sengi','senna','senor','sensa',
  'sensi','senvy','senza','sepad','sepal','sepic','sepoy','septa','serac','serai',
  'seral','sered','serer','seres','serge','seric','serin','serks','seron','serow',
  'serra','serre','serrs','serry','servo','sesey','sessa','setae','setal','seton',
  'sewan','sewar','sewel','sewen','sewin','sexer','sexto','seyen','shads','shahs',
  'shako','shakt','shalm','shaly','shama','shand','shans','shaps','sharn','shash',
  'shaul','shawn','shaws','shaya','shays','shchi','sheaf','sheal','sheas','sheel',
  'shend','shent','sheol','sherd','shere','shets','sheva','shewn','shews','shiai',
  'shiel','shill','shily','shins','shirr','shirs','shish','shiso','shist','shite',
  'shits','shiur','shiva','shive','shivs','shlep','shlub','shoat','shoed','shoer',
  'shogi','shogs','shoji','shojo','shola','shoon','shope','shorl','shote','shott',
  'showd','shoyu','shris','shrow','shtik','shtum','shtup','shule','shuln','shura',
  'shute','shwas','sials','sibbs','sibyl','sices','sicht','sicko','sidas','sidha',
  'sidhe','sield','siens','sient','sieth','sieur','sigil','sigla','signa','sijos',
  'sikas','siker','sikes','silds','silen','siler','silex','simar','simas','simba',
  'simis','simul','sinhs','sinky','siped','sippy','siree','sirih','siris','siroc',
  'sirra','sirup','sisal','sista','sitar','sithe','sitka','situp','situs','sixer',
  'sixmo','sixte','sizar','sizel','sizer','skags','skail','skald','skank','skart',
  'skats','skatt','skean','skear','skeds','skeed','skeef','skeen','skeer','skees',
  'skegg','skegs','skein','skelf','skell','skelm','skelp','skene','skens','skeos',
  'skeps','skets','skewi','skied','skiey','skimo','skink','skint','skios','skirl',
  'skirr','skite','skive','skivy','sklim','skoal','skoff','skogs','skool','skort',
  'skosh','skran','skrik','skued','skuer','skyey','skyfs','skyre','skyrs','skyte',
  'slabs','slade','slaes','slaid','slake','slane','slank','slart','slaty','slaws',
  'slays','slebs','sleds','sleer','slews','sleys','slier','slims','slipe','slipt',
  'slish','slive','sloan','slobs','sloes','slogs','sloid','slojd','slomo','sloom',
  'sloot','slopy','slorm','slove','sloyd','slubb','slubs','slued','slues','sluff',
  'slugs','sluit','slurb','sluse','slyer','slype','smaak','smaik','smalm','smalt',
  'smaze','smeek','smees','smeik','smeke','smerk','smews','smirr','smirs','smogs',
  'smoko','smolt','smoor','smoot','smore','smorg','smout','smowt','smurs','smush',
  'snabs','snafu','snarf','snark','snars','snary','snash','snath','snaws','snead',
  'sneap','snebs','sneck','sneed','snees','snell','snibs','snied','snies','snift',
  'snigs','snipy','snirt','snobs','snods','snoek','snoep','snogs','snoke','snood',
  'snook','snool','snots','snowk','snubs','snush','snyes','soaks','soaps','soare',
  'soave','sobas','socas','soces','socko','socks','socle','sodas','soddy','sodic',
  'sofar','softa','softs','softy','soger','soils','soily','sojas','sojus','sokah',
  'soken','sokes','sokol','solah','solan','solas','solde','soldi','soldo','solei',
  'soler','solon','solum','solus','soman','somas','sonde','sonly','sonse','sonsy',
  'sooey','sooks','sooky','soole','sools','sooms','soops','soote','sophs','sophy',
  'sopor','sopra','soral','soras','sorbo','sorbs','sorda','sordo','sored','soree',
  'sorel','sorex','sorgo','sorns','sorra','sorta','sorus','soths','sotol','souct',
  'souks','soums','souse','souts','sowar','sowce','sowff','sowfs','sowle','sowls',
  'sowms','sownd','sowne','sowps','sowse','sowth','soyle','soyuz','sozin','spacy',
  'spado','spaed','spaer','spaes','spags','spahi','spail','spait','spake','spald',
  'spale','spall','spalt','spane','spang','spard','spart','spaul','spawl','spayd',
  'spaza','spazz','speal','spean','speat','spect','speel','speer','speil','speir',
  'speks','speld','spelk','speos','spets','speug','spial','spica','spick','spics',
  'spide','spier','spiff','spifs','spile','spims','spink','spirt','spiry','spitz',
  'spivs','splog','spode','spods','spoom','spoot','spork','sposh','sprad','sprag',
  'spred','sprew','sprit','sprod','sprog','sprug','spuds','spued','spuer','spues',
  'spugs','spule','spume','spumy','spyal','spyre','squab','squaw','squeg','squit',
  'squiz','stabs','stade','staig','stane','stang','staph','staps','starn','starr',
  'stats','staun','staws','stean','stear','stedd','stede','steds','steek','steem',
  'steen','steil','stela','stele','stell','steme','stend','steno','stent','stept',
  'stere','stets','stewy','steys','stich','stied','sties','stilb','stile','stime',
  'stims','stimy','stipa','stipe','stire','stirk','stirp','stive','stivy','stoae',
  'stoai','stoas','stoat','stobs','stoep','stogy','stoit','stoln','stoma','stond',
  'stong','stonk','stonn','stook','stoor','stope','stopt','stoss','stots','stott',
  'stoun','stoup','stown','stowp','strad','strae','strag','strak','strep','stria',
  'strig','strim','strop','strow','stroy','stubs','stude','stull','stulm','stumm',
  'stums','stupa','stupe','sture','sturt','styed','styes','styli','stylo','styme',
  'stymy','styre','styte','subah','subas','subby','suber','subha','succi','sucky',
  'sucre','sudds','sudor','suede','suent','suers','sugan','sughs','sugos','suhur',
  'suids','suint','sujee','sukhs','sukuk','sulci','sulfa','sulfo','sulph','sulus',
  'sumis','summa','sumph','sunis','sunks','sunna','sunns','sunup','supes','supra',
  'sural','suras','surat','surds','sured','surfy','surgy','surra','sused','suses',
  'susus','sutor','sutra','sutta','swack','swads','swage','swags','swail','swale',
  'swaly','swamy','swank','swapt','sward','sware','swarf','swart','swayl','sweal',
  'swede','sweed','sweel','sweer','swees','sweir','swelt','swerf','sweys','swies',
  'swile','swink','swire','swith','swits','swive','swizz','swobs','swole','swoln',
  'swops','swopt','swoun','sybbe','syboe','sybow','sycee','syces','sycon','syens',
  'syker','sykes','sylis','sylph','sylva','symar','synch','synds','syned','syped',
  'sypes','syphs','syrah','syren','sysop','syver',
  // T
  'taals','taata','taber','tabes','tabid','tabis','tabla','tabor','tabun','tabus',
  'tacan','taces','tacet','tache','tacho','tachs','taels','tafia','taggy','tagma',
  'tahas','tahrs','taiga','taigs','taiko','tains','taira','taish','taits','tajes',
  'takas','takhi','takin','takis','takky','talak','talaq','talar','talas','talcs',
  'talcy','talea','taler','talky','talls','talma','talpa','taluk','talus','tamal',
  'tamin','tamis','tammy','tanas','tanga','tangi','tangs','tanhs','tanka','tanky',
  'tanna','tanti','tanto','tanty','tapas','tapen','tapes','tapet','tapis','tappa',
  'tapus','taras','tardo','tared','targa','targe','tarns','taroc','tarok','tarre',
  'tarsi','tasar','tased','taser','tases','tassa','tasse','tasso','tatar','tater',
  'taths','tatie','tatou','tatus','taube','tauld','tauon','taupe','tauts','tavah',
  'tavas','taver','tawai','tawas','tawie','tawse','tawts','taxol','taxon','taxor',
  'taxus','tayra','tazza','tazze','teade','teads','teaed','teaze','tecta','teels',
  'teend','teene','teens','teeny','teers','teffs','teggs','tegua','tegus','tehrs',
  'teiid','teils','teind','teins','telae','telco','teles','telia','telic','teloi',
  'telos','temed','temes','temse','tendu','tenes','tenge','tenia','tenne','tenno',
  'tenny','tenty','tenue','tepal','tepas','tepoy','terai','terce','terek','teres',
  'terfe','terfs','terga','terne','terts','testa','teste','tetes','teths','tetri',
  'teuch','teugh','tewed','tewel','tewit','texas','thack','thagi','thaim','thale',
  'thali','thana','thang','thanx','tharm','thawy','thebe','theca','theed','theek',
  'thees','thegn','theic','thein','thelf','thema','theow','thesp','thete','thewy',
  'thigs','thilk','thill','thiol','thirl','thoft','thole','tholi','thoro','thorp',
  'thowl','thrae','thraw','thrid','thrip','thuds','thuja','thunk','thurl','thuya',
  'thymi','thymy','tians','tiars','tical','ticca','ticed','tices','tichy','ticky',
  'tiddy','tided','tifos','tifts','tiges','tigon','tikas','tikis','tikka','tilak',
  'tiler','tilly','tilth','timbo','timed','timon','timps','tinas','tinct','tinds',
  'tinea','tined','tings','tinks','tinty','tipis','tippy','tirls','tiros','tirrs',
  'titch','titer','titis','titre','titty','titup','tiyin','tiyns','tizes','tizzy',
  'toady','toaze','tocky','tocos','todde','toeas','toffs','toffy','tofts','tofus',
  'togae','togas','toged','toges','togue','tohos','toile','toing','toise','toits',
  'tokay','toked','toker','tokes','tokos','tolan','tolar','tolas','toled','toles',
  'tolly','tolts','tolus','tolyl','toman','tombs','tomes','tomia','tomos','tondi',
  'tondo','toney','tonka','tonks','tonne','tools','tooms','toons','toots','topee',
  'topek','topes','tophe','tophi','tophs','topis','topoi','topps','toque','toran',
  'toras','torcs','tores','torii','toros','torot','torrs','torse','torsi','torsk',
  'torta','torte','tosas','tosed','toses','toshy','tossy','toter','totty','touks',
  'touns','touse','tousy','touze','touzy','towie','towny','towse','towsy','towts',
  'towze','towzy','toyed','toyer','toyon','toyos','tozed','tozes','tozie','trabs',
  'trads','traik','trank','tranq','trant','trape','traps','trapt','trass','trats',
  'tratt','trave','trayf','treck','treed','treen','trefa','treif','trema','trems',
  'trest','treys','triac','tride','triff','trigo','trild','trill','trins','triol',
  'trior','tripy','trist','troad','troak','troat','trock','trode','trods','trogs',
  'troke','tromp','trona','tronc','trone','tronk','trons','trooz','troth','trows',
  'trugo','trugs','trull','tryke','tryma','tryps','tsade','tsadi','tsked','tsuba',
  'tsubo','tuans','tuart','tuath','tubae','tubar','tubby','tubed','tufas','tuffe',
  'tufts','tufty','tugra','tuile','tuina','tuism','tuktu','tulpa','tulsi','tumid',
  'tumps','tumpy','tunds','tungs','tunny','tupek','tupik','tuple','tuque','turme',
  'turms','turnt','tushy','tusky','tutee','tutti','tutty','tutus','tuyer','twaes',
  'twals','twank','tways','tweel','tween','tweep','tweer','twerk','twier','twilt',
  'twink','twiny','twire','twirp','twite','twoer','twyer','tyees','tyers','tyiyn',
  'tyler','tymps','tynde','tyned','tynes','typey','typps','typto','tyran','tyred',
  'tyros','tythe','tzars',
  // U
  'udals','udons','ugali','uhlan','uhuru','ukase','ulama','ulans','ulema','ulmin',
  'ulnad','ulnae','ulnas','ulpan','ulvas','ulyie','ulzie','umbel','umber','umble',
  'umbos','umbre','umiac','umiak','umiaq','ummah','ummas','umped','umphs','umpie',
  'umpty','umrah','umras','unapt','unary','unaus','unbag','unban','unbar','unbed',
  'unbid','unbox','uncap','unces','uncia','uncos','uncoy','uncus','undam','undee',
  'undos','undug','uneth','unfix','ungag','unget','ungod','ungot','ungum','unhat',
  'unhip','unica','unjam','unked','unket','unkid','unlaw','unlay','unled','unlet',
  'unlid','unman','unmew','unmix','unpay','unpeg','unpen','unpin','unred','unrid',
  'unrig','unrip','unsaw','unsay','unsee','unsew','unsex','unsod','untax','untin',
  'unwet','unwit','unwon','upbow','upbye','updos','updry','upend','upjet','uplay',
  'upled','uplit','upran','uprun','upsee','upsey','uptak','upter','uptie','uraei',
  'urali','uraos','urare','urari','urase','urate','urbex','urbia','urdee','ureal',
  'ureas','uredo','ureic','urena','urent','urged','urger','urial','urite','urman',
  'urnal','urped','ursae','ursid','urson','urubu','urvas','usnea','usque','usure',
  'uveal','uveas','uvula',
  // V
  'vacua','vaded','vades','vagal','vagus','vaire','vairs','vairy','vakas','vakil',
  'valis','valse','vampy','vanda','vangs','vants','vaped','vaper','vapes','varan',
  'varas','vardy','varec','vares','varia','varix','varna','varus','varve','vasal',
  'vasts','vasty','vatic','vatus','vauch','vaute','vauts','vawte','vaxes','veale',
  'vealy','veena','veeps','veers','veery','veges','vegie','vegos','vehme','veily',
  'velar','velds','veldt','veles','velum','venae','vends','vendu','veney','venge',
  'venin','venus','verra','verry','verst','vertu','vespa','vetch','vexed','vexer',
  'vexil','vezir','vials','viand','vibes','vibex','vibey','viced','vichy','viers',
  'viewy','vifda','viffs','vigas','vigia','vilde','villi','vills','vimen','vinal',
  'vinas','vinca','vined','viner','vinew','vinic','vints','viold','viols','vired',
  'vireo','virga','virge','virid','virls','virtu','vised','vises','visie','visne',
  'vison','visto','vitae','vitex','vitro','vitta','vivat','vivda','viver','vives',
  'vizir','vizor','vleis','vlies','vlogs','voars','vocab','voces','voddy','vodou',
  'vodun','voema','vogie','voile','voips','volae','volar','voled','volet','volks',
  'volta','volte','volti','volva','volve','vomer','voted','vouge','voulu','vower',
  'voxel','vozhd','vraic','vrils','vroom','vrous','vrouw','vrows','vuggs','vuggy',
  'vughs','vughy','vulgo','vulns','vulva','vutty',
  // W
  'waacs','wacke','wacko','wacks','wadds','waddy','waded','wader','wades','wadge',
  'wadis','waffs','wafts','waged','wagga','wagyu','wahoo','waide','waift','wains',
  'wairs','waite','wakas','waked','waken','waker','wakfs','waldo','walds','waler',
  'walie','walis','walla','walty','wamed','wames','wamus','wands','wanes','waney',
  'wangs','wanks','wanky','wanle','wanly','wanna','wanty','wanze','waqfs','warbs',
  'warby','wards','wared','warez','warks','warre','warst','wases','washy','wasms',
  'wasps','waspy','wasts','watap','wauff','waugh','wauks','waulk','wauls','waurs',
  'waved','wavey','wawas','wawes','wawls','waxer','wayed','wazir','wazoo','weald',
  'weamb','webby','weber','wecht','wedel','wedgy','weeds','weeke','weels','weems',
  'weens','weeny','weepy','weest','weete','weets','wefte','wefts','weids','weils',
  'weise','weize','wekas','welke','welks','welkt','wells','welly','welts','wembs',
  'wends','wenge','wenny','wents','weros','wersh','wetas','wetly','wexed','whamo',
  'whang','whaps','whare','whata','whaup','whaur','wheal','whear','wheen','wheep',
  'wheft','whelk','whelm','whens','whets','whews','wheys','whids','whift','whigs',
  'whilk','whins','whios','whipt','whirr','whirs','whish','whiss','whist','whits',
  'whity','whomp','whoof','whoot','whops','whorl','whort','whoso','whows','whump',
  'whups','whyda','wicca','wicks','wicky','widdy','wides','wiels','wifed','wifes',
  'wifey','wifie','wifty','wigan','wigga','wikis','wilco','wilds','wiled','wiles',
  'wilga','wilis','wilja','wills','wimps','wined','winey','winge','wingy','winna',
  'winns','winze','wiper','wirra','wisha','wisps','wists','witan','wited','withe',
  'withs','withy','wiver','wizen','wizes','woads','woald','wocks','wodge','woful',
  'wojus','wokka','wolds','wolly','wolve','wombs','womby','womyn','wonga','wongi',
  'wonts','wooed','woofy','woold','wools','woons','woops','woopy','woose','woosh',
  'wootz','worms','wormy','worts','wowed','wowee','woxen','wrang','wrapt','wrast',
  'wrate','wrawl','wrick','wried','wrier','wries','writs','wroke','wroot','wryer',
  'wuddy','wudus','wulls','wurst','wuses','wushu','wussy','wuxia','wyled','wyles',
  'wynds','wynns','wyted','wytes',
  // X Y Z
  'xebec','xenia','xenic','xeric','xerox','xerus','xylan','xylem','xylic','xylol',
  'xylyl','yaars','yabba','yabby','yacca','yacks','yaffs','yager','yages','yagis',
  'yahoo','yaird','yakka','yakow','yamen','yampy','yamun','yangs','yapok','yapon',
  'yapps','yappy','yarak','yarco','yarer','yarfa','yarks','yarns','yarrs','yarta',
  'yarto','yauds','yauld','yaups','yawey','yawns','yawny','yawps','ycled','ycond',
  'yeads','yealm','yeans','yeard','yecch','yechs','yechy','yedes','yeeds','yeesh',
  'yeggs','yelks','yelms','yelts','yenta','yente','yerba','yerds','yerks','yeses',
  'yesks','yests','yesty','yetis','yetts','yeuks','yeuky','yeven','yeves','yewen',
  'yexed','yexes','yiked','yills','yince','yipes','yippy','yirds','yirks','yirrs',
  'yirth','yites','yitie','ylems','yobbo','yobby','yocks','yodhs','yodle','yogas',
  'yogee','yoghs','yogic','yogin','yoick','yojan','yoker','yokul','yomim','yomps',
  'yonic','yonis','yonks','yoofs','yoops','yorks','yorps','youks','yourn','yourt',
  'youse','yowed','yowes','yowie','yowls','yowza','yuans','yucas','yucch','yucko',
  'yucks','yucky','yufts','yukas','yuked','yukes','yukky','yukos','yulan','yummo',
  'yumps','yupon','yuppy','yurta','yurts','yuzus','zabra','zacks','zaida','zaidy',
  'zaire','zakat','zaman','zambo','zamia','zanja','zante','zanza','zanze','zarfs',
  'zaris','zatis','zayin','zazen','zeals','zebec','zebub','zebus','zedas','zeins',
  'zendo','zerda','zerks','zetas','zexes','zezes','zibet','ziffs','zilas','zilch',
  'zilla','zills','zimbi','zimbs','zinco','zineb','zinke','zinky','zippo','ziram',
  'zitis','zizel','zizit','zlote','zoaea','zobos','zobus','zocco','zoeae','zoeal',
  'zoeas','zoism','zoist','zombi','zonae','zonda','zoner','zonks','zooea','zooey',
  'zooid','zooks','zoons','zooty','zoppa','zoppo','zoril','zoris','zouks','zowee',
  'zowie','zulus','zupan','zupas','zuppa','zurfs','zuzim','zygal','zygon','zymic',
]

// 일반 영단어 추가 — 자주 입력하지만 위 목록에 없는 단어들
const EXTRA2: string[] = [
  // 일상 명사
  'about','above','abuse','adult','after','again','agree','ahead','aisle','alarm',
  'album','alert','alike','alive','alley','alone','along','aloud','aloft','alter',
  'among','angel','anime','annoy','aorta','apple','apply','arena','argue','asked',
  'attic','audio','awful','axles',
  // B
  'badly','baked','baker','bakes','balls','bands','bangs','banks','barks','based',
  'basis','batch','baths','baton','beats','began','begin','being','bikes','bills',
  'birds','bites','blown','blues','blunt','boats','bones','books','boots','bossy',
  'bowed','boxes','boys','brats','brave','bread','broke','broom','burns',
  // C
  'caged','calls','calmly','canal','cards','cares','cells','chain','chose','cited',
  'claim','clams','claps','claws','clays','clear','clerk','cloth','clown','clubs',
  'coals','coast','colds','coils','comes','comic','cooks','coops','cores','costs',
  'couch','could','crows','curly',
  // D
  'daily','dairy','dares','deals','decay','decks','decor','deeds','dense','depot',
  'devil','dicey','dirty','disco','dodge','doing','dolls','donkey','doors','draws',
  'dried','dries','drool','drops','drums','ducks','ducky','dumps','dusty',
  // E
  'eager','early','eased','eaten','eight','elbow','elite','empty','ended','enjoy',
  'enter','equal','error','essay','event','every','exact','exalt','exams','exist',
  'extra',
  // F
  'facts','fails','faked','falls','false','fangs','farms','favor','feels','ferry',
  'fiery','fills','films','finds','fired','fires','fixed','fixes','flags','flame',
  'flank','flash','flung','flute','focal','foggy','folks','foods','fools','foray',
  'forms','forum','frees','fresh','fully','funny',
  // G
  'gains','games','gangs','gates','gauge','genes','girl','gives','glare','gleam',
  'gloomy','goals','going','gonna','goods','goons','grabs','grains','greens','grins',
  'grips','groan','growl','grown','gruel','gruff','gulls','gummy','gummy',
  // H
  'habit','hails','halls','hands','hangs','happy','harms','haunt','heads','heady',
  'heals','heavy','heels','hello','helps','herbs','hikes','hills','hints','holds',
  'holly','honey','honor','hopes','horns','house','hovel','human','humid','hunts',
  // I
  'ideal','idols','image','inbox','inner','input','iotas','issue','items',
  // J
  'jails','jelly','jerky','joins','joins','jokes','jolly','jokey',
  // K
  'kayak','keeps','kicks','kills','kinds','kings','kitty','kneel','knelt',
  // L
  'lacks','lakes','lamps','lands','lapel','leaky','leads','leafy','leapt','legal',
  'level','light','likes','limbs','links','lists','lived','lives','local','looks',
  'loose','lowly','lusts',
  // M
  'makes','males','malls','marks','match','meals','means','meets','mends','merry',
  'minds','mine','mixed','mixes','moist','money','monks','mood','moves','muddy',
  // N
  'names','nerds','nests','newly','nicer','night','nifty','nixed','noble','norms',
  'noted','novel','nurse',
  // O
  'often','older','onset','opens','optic','outer','oven','owned',
  // P
  'packs','pages','pains','pairs','panel','parks','parts','paths','pawns','penny',
  'perks','phase','picks','piney','pipes','place','plans','plots','plows','pokey',
  'polls','pools','posts','pouty','power','prior','probe','prone','prose','proud',
  'proves','prowl','pulls','pumps','purse','pushy',
  // R
  'races','racks','rails','rains','raked','ranks','rated','rates','realm','reeds',
  'reeks','reels','relay','rents','rides','right','rings','roads','roofs','rooms',
  'roots','ropes','roost','ruler','rules','rural','rusty',
  // S
  'sadly','safes','sages','sandy','saves','scars','seeks','seems','sells','sends',
  'sense','shade','shaky','shall','shame','share','shows','shrug','sided','sides',
  'siege','signs','silky','silly','since','skies','skill','skins','slick','slops',
  'smack','small','smart','smash','smell','smile','smoke','sneak','sniff','snore',
  'soapy','socks','solar','solid','solve','songs','sorts','spare','spark','speed',
  'spend','spill','spine','split','spook','spoon','spore','spoke','spray','squat',
  'stack','stage','stain','stale','stand','stark','start','steal','steep','steps',
  'stern','still','stone','store','story','strap','straw','stray','strip','stuck',
  'study','style','sugar','suits','super','surly','swamp','swear','sweep','sweet',
  'swept','swift','swords',
  // T
  'taken','talks','tasks','taste','taxes','teach','tells','texts','their','thick',
  'thing','think','those','threw','thumb','tired','title','today','token','topaz',
  'total','toxic','track','trade','trail','train','trait','trash','treat','trend',
  'trial','trick','tried','truck','truly','trunk','truth','tummy','turns','twice',
  'twist',
  // U
  'under','union','unite','upper','upset','using','usual','utter',
  // V
  'valor','value','veins','venom','verge','verse','visit','vocal','voice','voter',
  // W
  'walks','walls','wants','warns','waste','watch','waves','weeds','weird','wells',
  'whole','wider','winds','wines','wings','witch','woman','women','world','worry',
  'worse','worst','worth','would','wrath','wreck','write','wrong','wrote',
  // X Y Z
  'yards','years','young','yours','youth','zones',
]

// 정답 단어 + 추가 허용 단어를 합쳐 유효 추측 집합 구성
export const VALID_WORDS = new Set([...ANSWERS, ...EXTRA_GUESSES, ...NYT_VALID, ...EXTRA2])

const EPOCH = new Date(2026, 5, 1).getTime() // 2026-06-01 기준일
const SHUFFLE_SEED = 20260601 // 고정 시드로 항상 동일한 순서 보장

// LCG 기반 시드 셔플 — 비슷한 단어가 연속으로 나오지 않도록 단어 목록을 섞음
function seededShuffle(arr: string[], seed: number): string[] {
  const a = [...arr]
  let s = seed >>> 0
  for (let i = a.length - 1; i > 0; i--) {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0
    const j = s % (i + 1)
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

const SHUFFLED = seededShuffle(ANSWERS, SHUFFLE_SEED)

export function getDailyWords(): [string, string] {
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const day = Math.floor((today.getTime() - EPOCH) / 86400000)
  const idx = (day * 2) % SHUFFLED.length
  return [SHUFFLED[idx], SHUFFLED[(idx + 1) % SHUFFLED.length]]
}

export type LetterState = 'correct' | 'present' | 'absent' | 'empty' | 'tbd'

export function evaluateGuess(guess: string, answer: string): ('correct' | 'present' | 'absent')[] {
  const result: ('correct' | 'present' | 'absent')[] = Array(5).fill('absent')
  const ansArr = answer.split('')
  const guessArr = guess.split('')

  guessArr.forEach((c, i) => {
    if (c === ansArr[i]) { result[i] = 'correct'; ansArr[i] = '#' }
  })
  guessArr.forEach((c, i) => {
    if (result[i] === 'correct') return
    const idx = ansArr.indexOf(c)
    if (idx !== -1) { result[i] = 'present'; ansArr[idx] = '#' }
  })
  return result
}
